apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: ytechnologies/to-do-app
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "4Gi"